let toan;
let li;
let hoa;
toan = prompt("Nhap diem Toan: ");
li = prompt("Nhap diem Li: ");
hoa = prompt("Nhap diem Hoa: ");
let T=parseInt(toan);
let L=parseInt(li);
let H=parseInt(hoa);
let DTB = (T + L + H)/3;
alert("DTB là: " + DTB);